version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ENVIRONMENT=local
      - SERVICE_ADDR=:8080
      - PG_DSN=host=db user=postgres password=docker dbname=postgres port=5432

volumes:
  postgres_data: