// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	result "github.com/nlsh710599/still-practice/internal/result"
	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// Health provides a mock function with given fields: ctx
func (_m *HealthService) Health(ctx context.Context) (result.HealthResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 result.HealthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (result.HealthResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) result.HealthResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(result.HealthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
